package airlineReservationSystem2021;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import modelClass.Flight;
import modelClass.Reservation;
import modelClass.User;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author amiras
 */
public class BookingDetails extends javax.swing.JFrame {

    private static Reservation reservation;

    /**
     * Creates new form frame
     */
    public BookingDetails(Flight flight, User user) {
        initComponents();

        reservation = new Reservation();
        reservation.setUser(user);
        reservation.getTicket().setFlight(flight);

        initData();
    }

    private void initData() {
        URL url;
        try {
            url = new URL(reservation.getTicket().getFlight().getImageUrl());
            BufferedImage bufferedImage = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(bufferedImage);
            Image imageFlight = icon.getImage();
            imageFlight = imageFlight.getScaledInstance(299, 166,
                    Image.SCALE_SMOOTH);

            imgFlightImage.setIcon(new ImageIcon(imageFlight));

        } catch (MalformedURLException ex) {
            Logger.getLogger(FlightItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FlightItem.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtFlightNo.setText(reservation.getTicket().getFlight().getFlightNo());
        txtTotalSeats.setText(String.valueOf(reservation.getTicket().getFlight().getTotalSeats()));
        txtBoardingDate.setText(reservation.getTicket().getFlight().getFlightNo());
        txtFrom.setText(reservation.getTicket().getFlight().getOrigin().getValue());
        txtTo.setText(reservation.getTicket().getFlight().getDestination().getValue());
        txtPrice.setText(String.valueOf(reservation.getTicket().getFlight().getPrice()));
        txtTotal.setText(String.valueOf(reservation.getTicket().calcTotalPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Insurance = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        imgFlightImage = new javax.swing.JLabel();
        txtFlightId = new javax.swing.JLabel();
        txtFlightNo = new javax.swing.JLabel();
        txtFlightId2 = new javax.swing.JLabel();
        txtTotalSeats = new javax.swing.JLabel();
        txtFlightId4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        txtFlightId3 = new javax.swing.JLabel();
        txtBoardingDate = new javax.swing.JLabel();
        txtFlightId5 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JLabel();
        txtFlightId6 = new javax.swing.JLabel();
        txtTo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        etSeat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        etYes = new javax.swing.JRadioButton();
        etNo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        etWeight = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lableARS = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        javax.swing.JButton btnProceedPayment = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(370, 404));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 404));

        imgFlightImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        txtFlightId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId.setText("Flight No           :");

        txtFlightNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightNo.setText("ds");

        txtFlightId2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId2.setText("Total Seats       :");

        txtTotalSeats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalSeats.setText("ds");

        txtFlightId4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFlightId4.setText("Price                :   RM");

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrice.setText("ds");

        txtFlightId3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId3.setText("Boarding Date  :");

        txtBoardingDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBoardingDate.setText("ds");

        txtFlightId5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId5.setText("From                :");

        txtFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFrom.setText("ds");

        txtFlightId6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId6.setText("To                    :");

        txtTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTo.setText("ds");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFlightId6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFlightId5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(imgFlightImage, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFlightId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFlightId2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFlightId4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFlightId3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBoardingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgFlightImage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId)
                    .addComponent(txtFlightNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId2)
                    .addComponent(txtTotalSeats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId3)
                    .addComponent(txtBoardingDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId5)
                    .addComponent(txtFrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId6)
                    .addComponent(txtTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId4)
                    .addComponent(txtPrice))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 210, 350, 404);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Choose Your Seat:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 240, 170, 24);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel6.setText("TICKET INFORMATION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 130, 395, 47);

        etSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "1B", "1C", "1D", "1E", "1F", "2A", "2B", "2C", "2D", "2E", "2F", "3A", "3B", "3C", "3D", "3E", "3F" }));
        etSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etSeatActionPerformed(evt);
            }
        });
        getContentPane().add(etSeat);
        etSeat.setBounds(710, 240, 93, 32);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Are you taking any insurans?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 300, 240, 24);

        Insurance.add(etYes);
        etYes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        etYes.setText("Yes");
        etYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etYesActionPerformed(evt);
            }
        });
        getContentPane().add(etYes);
        etYes.setBounds(770, 300, 57, 33);

        Insurance.add(etNo);
        etNo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        etNo.setSelected(true);
        etNo.setText("No");
        etNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNoActionPerformed(evt);
            }
        });
        getContentPane().add(etNo);
        etNo.setBounds(710, 300, 49, 33);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Enter your luggage weight");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 370, 206, 24);

        etWeight.setText("0");
        etWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etWeightActionPerformed(evt);
            }
        });
        etWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etWeightKeyReleased(evt);
            }
        });
        getContentPane().add(etWeight);
        etWeight.setBounds(710, 360, 94, 32);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("KG");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(810, 370, 26, 24);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Your total payment is");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 430, 167, 24);

        txtTotal.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtTotal.setText("Total");
        getContentPane().add(txtTotal);
        txtTotal.setBounds(650, 430, 80, 24);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(null);

        lableARS.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        lableARS.setForeground(new java.awt.Color(255, 255, 255));
        lableARS.setText("ARS");
        jPanel2.add(lableARS);
        lableARS.setBounds(100, 30, 80, 40);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("jLabel1");
        btnBack.setMaximumSize(new java.awt.Dimension(60, 60));
        btnBack.setMinimumSize(new java.awt.Dimension(60, 60));
        btnBack.setPreferredSize(new java.awt.Dimension(60, 60));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(20, 20, 60, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1060, 90);

        btnProceedPayment.setBackground(new java.awt.Color(0, 102, 255));
        btnProceedPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProceedPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnProceedPayment.setText("Proceed Payment");
        btnProceedPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnProceedPayment);
        btnProceedPayment.setBounds(460, 510, 270, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hero.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 44, 1060, 685);

        setSize(new java.awt.Dimension(1078, 787));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void etSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etSeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etSeatActionPerformed

    private void etYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etYesActionPerformed
        resetTotal();
    }//GEN-LAST:event_etYesActionPerformed

    private void etNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNoActionPerformed
        resetTotal();
    }//GEN-LAST:event_etNoActionPerformed

    private void btnProceedPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedPaymentActionPerformed

//        Update data in ticket
        reservation.getTicket().setSeatNo(etSeat.getSelectedItem().toString());
        reservation.getTicket().setLuggageWeight(Double.parseDouble(etWeight.getText()));
        reservation.getTicket().setIsTakeInsurance(etYes.isSelected());

        new PaymentGatewayLogin(reservation)
                .setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnProceedPaymentActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        new ChooseFlight(reservation.getUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void etWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etWeightActionPerformed

    private void etWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etWeightKeyReleased
        resetTotal();
    }//GEN-LAST:event_etWeightKeyReleased

    public void resetTotal() {
        if (!etWeight.getText().equals("")) {
            reservation.getTicket().setLuggageWeight(Double.parseDouble(etWeight.getText()));
            reservation.getTicket().setIsTakeInsurance(etYes.isSelected());
//            Recalculate Price
            txtTotal.setText(String.valueOf(reservation.getTicket().calcTotalPrice()));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Insurance;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnBack;
    private javax.swing.JRadioButton etNo;
    private javax.swing.JComboBox<String> etSeat;
    private javax.swing.JTextField etWeight;
    private javax.swing.JRadioButton etYes;
    private javax.swing.JLabel imgFlightImage;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lableARS;
    private javax.swing.JLabel txtBoardingDate;
    private javax.swing.JLabel txtFlightId;
    private javax.swing.JLabel txtFlightId2;
    private javax.swing.JLabel txtFlightId3;
    private javax.swing.JLabel txtFlightId4;
    private javax.swing.JLabel txtFlightId5;
    private javax.swing.JLabel txtFlightId6;
    private javax.swing.JLabel txtFlightNo;
    private javax.swing.JLabel txtFrom;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtTo;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTotalSeats;
    // End of variables declaration//GEN-END:variables

}
