package airlineReservationSystem2021;

import java.awt.GridLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import modelClass.ComboItem;
import modelClass.Flight;
import modelClass.GateEnum;
import modelClass.User;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author amiras
 */
public class ChooseFlight extends javax.swing.JFrame {

    private User user;

    /**
     * Creates new form frame
     */
    public ChooseFlight(User user) {
        initComponents();
        this.user = user;
        initData();
    }

    private void initData() {
        // Get all location from airports table
        try {
            // Check is the credentials correct
            String query = "SELECT * FROM airports";

            // create the mysql insert preparedstatement
            PreparedStatement ps = InitDb.getConnection().prepareStatement(query);

            // execute the preparedstatement
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                cbOrigin.addItem(new ComboItem(rs.getString("id"), rs.getString("name")));
                cbDestination.addItem(new ComboItem(rs.getString("id"), rs.getString("name")));
            }

            // To avoid same origin and Destination
            cbDestination.setSelectedIndex(1);

            InitDb.close();
            rs.close();
            ps.close();

        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }

        getFlights();
    }

    private void getFlights() {
        // Get list of flight
        try {
            panelFlight.removeAll();

            String query = "select `flights`.*, `or`.`name` as `origin_name`, `de`.`name` as `destination_name`, `or`.`id` as `origin_id`, `de`.`id` as `destination_id` from `flights` inner join `airports` as `or` on `or`.`id` = `flights`.`origin` inner join `airports` as `de` on `de`.`id` = `flights`.`destination` WHERE `origin` LIKE ? AND `destination` LIKE ? ";
            int count = 0;
            // Declare and init ArrayList
            ArrayList<FlightItem> listFlightItem = new ArrayList<>();

            PreparedStatement ps = InitDb.getConnection().prepareStatement(query);

            // Downcasting from Object returned to ComboItem Model and set to query
            ps.setString(1, ((ComboItem) cbOrigin.getSelectedItem()).getKey());
            ps.setString(2, ((ComboItem) cbDestination.getSelectedItem()).getKey());

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                ++count;

                Flight flight = new Flight();
                flight.setFlightNo(rs.getString("flight_no"));
                flight.setFlightId(rs.getInt("id"));
                flight.setTotalSeats(rs.getInt("total_seats"));
                flight.setPrice(rs.getDouble("price"));
                flight.setOrigin(new ComboItem(rs.getString("origin_id"), rs.getString("origin_name")));
                flight.setDestination(new ComboItem(rs.getString("destination_id"), rs.getString("destination_name")));
                flight.setBoardingDate(rs.getDate("boarding_date"));
                flight.setGate(GateEnum.valueOf(rs.getString("gate")));
                flight.setImageUrl(rs.getString("image_url"));

                FlightItem flightItem = new FlightItem(flight, this, user);
                listFlightItem.add(flightItem);

            }
            // if there is data
            if (count > 0) {
                GridLayout glMenu = new GridLayout(0, count);
                panelFlight.setLayout(glMenu);

                for (FlightItem flightItem : listFlightItem) {
                    panelFlight.add(flightItem);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No result founds.");
            }

            panelFlight.revalidate();
            panelFlight.repaint();

            InitDb.close();
            rs.close();
            ps.close();

        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtFlightId3 = new javax.swing.JLabel();
        txtFlightId2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelFlight = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        cbOrigin = new javax.swing.JComboBox<>();
        cbDestination = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        etTitle1 = new javax.swing.JLabel();
        btnHome1 = new javax.swing.JLabel();
        btnViewReservation = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1056, 731));
        getContentPane().setLayout(null);

        txtFlightId3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFlightId3.setText("From");
        getContentPane().add(txtFlightId3);
        txtFlightId3.setBounds(60, 160, 140, 17);

        txtFlightId2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFlightId2.setText("To");
        getContentPane().add(txtFlightId2);
        txtFlightId2.setBounds(410, 160, 140, 17);

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(950, 430));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(950, 430));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(950, 430));

        panelFlight.setForeground(new java.awt.Color(240, 240, 240));
        panelFlight.setOpaque(false);

        javax.swing.GroupLayout panelFlightLayout = new javax.swing.GroupLayout(panelFlight);
        panelFlight.setLayout(panelFlightLayout);
        panelFlightLayout.setHorizontalGroup(
                panelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 952, Short.MAX_VALUE));
        panelFlightLayout.setVerticalGroup(
                panelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 432, Short.MAX_VALUE));

        jScrollPane1.setViewportView(panelFlight);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 250, 950, 430);

        btnSearch.setBackground(new java.awt.Color(0, 102, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(5, 23));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(760, 180, 250, 36);

        cbOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOriginActionPerformed(evt);
            }
        });
        getContentPane().add(cbOrigin);
        cbOrigin.setBounds(60, 182, 333, 37);

        cbDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinationActionPerformed(evt);
            }
        });
        getContentPane().add(cbDestination);
        cbDestination.setBounds(410, 180, 333, 37);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(null);

        etTitle1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        etTitle1.setForeground(new java.awt.Color(255, 255, 255));
        etTitle1.setText("ARS");
        jPanel2.add(etTitle1);
        etTitle1.setBounds(30, 20, 80, 40);

        btnHome1.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(255, 255, 255));
        btnHome1.setText("HOME");
        jPanel2.add(btnHome1);
        btnHome1.setBounds(730, 40, 50, 20);

        btnViewReservation.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnViewReservation.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReservation.setText("MY RESERVATION");
        btnViewReservation.setToolTipText("");
        btnViewReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewReservationMouseClicked(evt);
            }
        });
        jPanel2.add(btnViewReservation);
        btnViewReservation.setBounds(800, 40, 146, 20);

        btnLogout.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        jPanel2.add(btnLogout);
        btnLogout.setBounds(960, 40, 70, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1060, 90);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hero.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 44, 1060, 685);

        setSize(new java.awt.Dimension(1070, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed
        getFlights();
    }// GEN-LAST:event_btnSearchActionPerformed

    private void cbDestinationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbDestinationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbDestinationActionPerformed

    private void cbOriginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbOriginActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbOriginActionPerformed

    private void btnViewReservationMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnViewReservationMouseClicked
        // TODO add your handling code here:
        new MyReservation(user).setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnViewReservationMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnHome1;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel btnViewReservation;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<ComboItem> cbDestination;
    private javax.swing.JComboBox<ComboItem> cbOrigin;
    private javax.swing.JLabel etTitle1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFlight;
    private javax.swing.JLabel txtFlightId2;
    private javax.swing.JLabel txtFlightId3;
    // End of variables declaration//GEN-END:variables

}
