/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlineReservationSystem2021;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import modelClass.Flight;
import modelClass.User;

/**
 *
 * @author Mohd Mohsin Ismail
 */
public class FlightItem extends javax.swing.JPanel {

    private Flight flight;
    private User user;
    private final JFrame jframe;

    /**
     * Creates new form FlightItem
     *
     * @param flight
     * @param jframe
     * @param user
     */
    public FlightItem(Flight flight, JFrame jframe, User user) {
        initComponents();
        this.flight = flight;
        this.user = user;
        this.jframe = jframe;

        URL url;
        try {
            url = new URL(flight.getImageUrl());
            BufferedImage bufferedImage = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(bufferedImage);
            Image imageFlight = icon.getImage();
            imageFlight = imageFlight.getScaledInstance(299, 166,
                    Image.SCALE_SMOOTH);

            imgFlightImage.setIcon(new ImageIcon(imageFlight));

        } catch (MalformedURLException ex) {
            Logger.getLogger(FlightItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FlightItem.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtFlightNo.setText(flight.getFlightNo());
        txtTotalSeats.setText(String.valueOf(flight.getTotalSeats()));
        txtPrice.setText(String.valueOf(flight.getPrice()));
        txtBoardingDate.setText(flight.getBoardingDateString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton btnChooseFlight = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imgFlightImage = new javax.swing.JLabel();
        txtFlightId = new javax.swing.JLabel();
        txtFlightNo = new javax.swing.JLabel();
        txtFlightId2 = new javax.swing.JLabel();
        txtTotalSeats = new javax.swing.JLabel();
        txtFlightId4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        txtFlightId3 = new javax.swing.JLabel();
        txtBoardingDate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(370, 404));
        setMinimumSize(new java.awt.Dimension(370, 404));

        btnChooseFlight.setBackground(new java.awt.Color(0, 102, 255));
        btnChooseFlight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChooseFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseFlight.setText("Choose Flight");
        btnChooseFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        imgFlightImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        txtFlightId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId.setText("Flight No           :");

        txtFlightNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightNo.setText("ds");

        txtFlightId2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId2.setText("Total Seats       :");

        txtTotalSeats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalSeats.setText("ds");

        txtFlightId4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFlightId4.setText("Price                :   RM");

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrice.setText("ds");

        txtFlightId3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFlightId3.setText("Boarding Date  :");

        txtBoardingDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBoardingDate.setText("ds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnChooseFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgFlightImage, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFlightId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFlightId2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFlightId4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFlightId3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBoardingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgFlightImage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId)
                    .addComponent(txtFlightNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId2)
                    .addComponent(txtTotalSeats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId3)
                    .addComponent(txtBoardingDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightId4)
                    .addComponent(txtPrice))
                .addGap(18, 18, 18)
                .addComponent(btnChooseFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFlightActionPerformed
        
        
        new BookingDetails(flight, user).setVisible(true);
        jframe.dispose();

    }//GEN-LAST:event_btnChooseFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFlightImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBoardingDate;
    private javax.swing.JLabel txtFlightId;
    private javax.swing.JLabel txtFlightId2;
    private javax.swing.JLabel txtFlightId3;
    private javax.swing.JLabel txtFlightId4;
    private javax.swing.JLabel txtFlightNo;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtTotalSeats;
    // End of variables declaration//GEN-END:variables
}
