/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlineReservationSystem2021;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelClass.GenderEnum;
import modelClass.Passenger;
import modelClass.User;
import modelClass.UserFactory;

/**
 *
 * @author Sarvess S/O Veeriyah
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        etUsername = new javax.swing.JTextField();
        etPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        etTitle1 = new javax.swing.JLabel();
        etTitle = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        etTitle2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(720, 0, 3, 770);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("WELCOME TO");
        getContentPane().add(label1);
        label1.setBounds(780, 70, 210, 36);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        label2.setText("ARS");
        getContentPane().add(label2);
        label2.setBounds(820, 120, 140, 80);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        label3.setText("Login");
        getContentPane().add(label3);
        label3.setBounds(750, 330, 280, 30);

        etUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(etUsername);
        etUsername.setBounds(750, 370, 280, 40);
        getContentPane().add(etPassword);
        etPassword.setBounds(750, 420, 280, 40);

        btnLogin.setBackground(new java.awt.Color(0, 102, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(750, 570, 270, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airplane.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, 70, 750, 600);

        btnSignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSignUp.setText("SIGNUP");
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
        });
        getContentPane().add(btnSignUp);
        btnSignUp.setBounds(750, 620, 270, 40);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(null);

        etTitle1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        etTitle1.setForeground(new java.awt.Color(255, 255, 255));
        etTitle1.setText("ARS");
        jPanel2.add(etTitle1);
        etTitle1.setBounds(30, 20, 80, 40);

        etTitle.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        etTitle.setForeground(new java.awt.Color(255, 255, 255));
        etTitle.setText("ARS");
        jPanel2.add(etTitle);
        etTitle.setBounds(30, 20, 80, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 90);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        label6.setText("Find a flight to your destination");
        getContentPane().add(label6);
        label6.setBounds(750, 220, 290, 30);

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(null);

        etTitle2.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        etTitle2.setForeground(new java.awt.Color(255, 255, 255));
        etTitle2.setText("Its more than just a trip");
        jPanel3.add(etTitle2);
        etTitle2.setBounds(30, 20, 510, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 640, 720, 90);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hero.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 20, 1060, 710);

        setSize(new java.awt.Dimension(1070, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void etUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        try {
            // Check is the credentials correct
            String query = "SELECT * FROM users WHERE username = ? AND password = ? LIMIT 1";

            // create the mysql insert prepared statement
            PreparedStatement ps = InitDb.getConnection().prepareStatement(query);
            ps.setString(1, etUsername.getText());
            ps.setString(2, String.valueOf(etPassword.getPassword()));

            // execute the preparedstatement
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
//                    Factory Design Pattern
                    UserFactory userFactory = new UserFactory();
//                    Retrieve user type from database
                    User user = userFactory.getUser(rs.getString("type"));

                    user.setId(rs.getString("id"));
                    user.setAge(rs.getInt("age"));
                    user.setEmail(rs.getString("email"));
                    user.setGender(GenderEnum.valueOf(rs.getString("gender")));
                    user.setIcNo(rs.getString("ic_number"));
                    user.setName(rs.getString("name"));
                    user.setPhoneNo("phone_number");

                    if ("Passenger".equalsIgnoreCase(user.getUserType())) {

//                        Downcasting
                        Passenger passenger = (Passenger) user;
                        passenger.setPassportNo(rs.getString("passport"));
                        passenger.setUsername(rs.getString("username"));

                        new ChooseFlight(user).setVisible(true);
                        this.dispose();
                    }

            } else {
                JOptionPane.showMessageDialog(null, "Credentials does not match any user records.");
            }

            InitDb.close();
            rs.close();
            ps.close();
        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        new SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnSignUp;
    private javax.swing.JPasswordField etPassword;
    private javax.swing.JLabel etTitle;
    private javax.swing.JLabel etTitle1;
    private javax.swing.JLabel etTitle2;
    private javax.swing.JTextField etUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
